Gulpfile has been rewritten. Closes #15
duffers20/Angular2-Template pull request #16
Opened 2016-09-21 15:50 UTC by duffers20

The gulpfile has been rewritten to handle situations where you wish to only watch and publish /src/app files, instead of publishing the entire app.

2016-09-22 13:35 UTC, GarethOates commented on Gulpfile.js
> +﻿const
Nice!

2016-09-22 13:38 UTC, GarethOates commented on Gulpfile.js
> +    return del(['dist/**']);
consider using paths.dest for consistency and so you only need to update the variable to change it.

2016-09-22 13:38 UTC, GarethOates commented on Gulpfile.js
> +        .pipe(gulp.dest('dist'));
similar story here and elsewhere.  Don't use hard-coded 'dist' string.

2016-09-22 13:39 UTC, GarethOates commented on Gulpfile.js
> +        .pipe(gulp.dest('dist/vendor'));
as above

2016-09-22 13:39 UTC, GarethOates commented on package.json
> -    "gulp-uglify": "^2.0.0",
Presume you removed the Uglify process because we're dealing with 'dev' builds here?

2016-09-22 13:40 UTC, GarethOates requested changes
Please make some changes regarding the use of 'dist' hard-coded versus the paths.dest variable.

2016-09-22 14:14 UTC, duffers20 commented on package.json
> -    "gulp-uglify": "^2.0.0",
Yeah, I stripped it right back so that we can get a good base script, to which we can add features like uglify/minify/bundling scripts etc.

2016-09-23 09:48 UTC, GarethOates approved these changes
That's better.

2016-09-23 09:48 UTC, merged